name: Build and Package AnatomyViewer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
      
    - name: Create DMG (macOS)
      if: runner.os == 'macOS'
      run: |
        ${JAVA_HOME}/bin/jpackage \
          --type dmg \
          --name AnatomyViewer \
          --input target \
          --main-jar Assignments-1.0-SNAPSHOT.jar \
          --main-class Project02.AnatomyViewer \
          --dest target/dist \
          --vendor "DrMohamedElsherif" \
          --app-version 1.0 \
          --icon src/main/resources/anatomy_icon.icns \
          --mac-package-identifier com.example.anatomyviewer \
          --mac-package-name AnatomyViewer
    
    - name: Create EXE (Windows)
      if: runner.os == 'Windows'
      run: |
        ${JAVA_HOME}\bin\jpackage ^
          --type msi ^
          --name AnatomyViewer ^
          --input target ^
          --main-jar Assignments-1.0-SNAPSHOT.jar ^
          --main-class Project02.AnatomyViewer ^
          --dest target/dist ^
          --vendor "DrMohamedElsherif" ^
          --app-version 1.0 ^
          --icon src/main/resources/anatomy_icon.ico ^
          --win-menu ^
          --win-shortcut
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: AnatomyViewer-${{ runner.os }}
        path: target/dist/*
